ALTER TABLE meter_readings
ADD COLUMN IF NOT EXISTS xls INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS a4_bw_net INT,
ADD COLUMN IF NOT EXISTS a3_bw_net INT,
ADD COLUMN IF NOT EXISTS a4_color_net INT,
ADD COLUMN IF NOT EXISTS a3_color_net INT;
