ALTER TABLE contracts
DROP COLUMN IF EXISTS a4_bw_price,
DROP COLUMN IF EXISTS a3_bw_price,
DROP COLUMN IF EXISTS a4_color_price,
DROP COLUMN IF EXISTS a3_color_price;

ALTER TABLE contracts
ADD COLUMN IF NOT EXISTS bw_price NUMERIC(10, 4) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS color_price NUMERIC(10, 4) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS excess_bw_price NUMERIC(10, 4) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS excess_color_price NUMERIC(10, 4) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS a4_price NUMERIC(10, 4) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS a3_price NUMERIC(10, 4) NOT NULL DEFAULT 0;
