ALTER TABLE billing_cycles
ADD COLUMN IF NOT EXISTS is_baseline BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS baseline_set_by UUID REFERENCES users(id),
ADD COLUMN IF NOT EXISTS baseline_set_at TIMESTAMPTZ;
